name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0

      - name: Print Kube info
        run: |
          kubectl cluster-info
          kubectl get node -o wide
          kubectl get pods -o wide -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}          
