name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: engineerd/setup-kind@v0.5.0
        with:
          config: .github/kind_config.yml
          image: kindest/node:v1.20.0

      - name: Print Kube info
        run: |
          echo "==== kubectl cluster-info"
          kubectl cluster-info
          echo "==== kubectl get node -o wide"
          kubectl get node -o wide
          echo "==== kubectl get pods -o wide -n kube-system"
          kubectl get pods -o wide -n kube-system
          echo "==== kubelet version"
          kubectl version
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}          
